version: '3.7'

services:
  turnkey3:
    build: .
    volumes:
      - mvs38j:/opt/hercules/mvs38j
    environment:
      - TZ=Japan/Tokyo
    ports:
      - 8081:8081
      - 3270:3270

volumes:
  mvs38j:

